# Generated by Django 3.0.5 on 2020-04-02 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('requires', models.ManyToManyField(blank=True, related_name='required_by', through='guides.Requirement', to='guides.Step')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text', models.TextField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.Step')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='required_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guides.Step'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requires',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guides.Step'),
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('optional', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.Guide')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.Step')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='guide',
            name='steps',
            field=models.ManyToManyField(blank=True, through='guides.GuideStep', to='guides.Step'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text', models.TextField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.Step')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
