# Generated by Django 3.0.5 on 2020-04-01 23:28

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('actions', sortedm2m.fields.SortedManyToManyField(help_text=None, to='guides.Action')),
                ('requirements', models.ManyToManyField(to='guides.Step')),
                ('verifications', sortedm2m.fields.SortedManyToManyField(help_text=None, to='guides.Verification')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('steps', sortedm2m.fields.SortedManyToManyField(help_text=None, to='guides.Step')),
            ],
        ),
    ]
