# Generated by Django 3.0.5 on 2020-04-02 00:03

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='steps',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='guides.Step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='actions',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='guides.Action'),
        ),
        migrations.AlterField(
            model_name='step',
            name='verifications',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='guides.Verification'),
        ),
    ]
