# Generated by Django 3.0.5 on 2020-04-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20200402_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
